build: false
version: 0.3.4.dev1.{build}
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:/get-pip.py"
  - ps: "git config --global core.autocrlf false" # always use unix lineendings
install:
  - "%PYTHON%/python.exe c:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe -q install -r requirements.txt"
test_script:
  - "%PYTHON%/python.exe setup.py test"


